[env]
TERM = "xterm-256color"

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMonoNL Nerd Font Mono"

size = 16

[general]
import = ["~/.config/alacritty/themes/themes/kanagawa_dragon.toml"]
