[tools]
bun = "latest"
clojure = "latest"
codex = "latest"
deno = "latest"
dotnet = "latest"
elixir = "latest"
erlang = "latest"
go = "latest"
java = "latest"
node = "latest"
opam = "latest"
php = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
scala = "latest"
zig = "latest"
