# Flexoki Dark colors, hardcoded (no dynamic theme system).

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = rgba(282726ff)
    path = ~/Pictures/wallpaper.png
    blur_passes = 3
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = rgba(343331cc)
    outer_color = rgba(4385BEff)
    outline_thickness = 4

    font_family = Adwaita Mono
    font_color = rgba(FFFCF0ff)

    placeholder_text = Enter Password
    check_color = rgba(879A39ff)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
