-- Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/Start/
-- Native Hyprland Lua config (see /usr/share/hypr/stubs/hl.meta.lua for the
-- full `hl` API). No external framework involved.

local hypr_dir = (os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/hypr"

dofile(hypr_dir .. "/envs.lua")
dofile(hypr_dir .. "/monitors.lua")
dofile(hypr_dir .. "/input.lua")
dofile(hypr_dir .. "/looknfeel.lua")
dofile(hypr_dir .. "/windowrules.lua")
dofile(hypr_dir .. "/bindings.lua")
dofile(hypr_dir .. "/autostart.lua")

-- Generated by hyprmoncfg (if installed), loaded last so nothing above can
-- override the applied monitor layout.
local hyprmoncfg = hypr_dir .. "/hyprmoncfg-monitors.lua"
local f = io.open(hyprmoncfg, "r")
if f then
  f:close()
  dofile(hyprmoncfg)
end
